baseURL = '/'
languageCode = 'en'
defaultContentLanguage = "en"
hasCJKLanguage = true
enableEmoji = true
title = 'Walk with Kev'
copyright = 'Kevin Bergin'
theme = 'hugo-theme-itheme'
paginate = 5
[params]
  defaultCover = ''
  email = 'kev@walkwithkev.com'
  [[params.socialMedia]]
    name = 'Youtube'
    url = 'https://www.youtube.com/@walkwithkev'
